#ifndef __VIRIncludeAll_h__
#define __VIRIncludeAll_h__

#include "VIRBase.hpp"
#include "KindType.hpp"

#include "AddressObjectDeclaration.hpp"
#include "AddressPragma.hpp"
#include "Array.hpp"
#include "AssignmentStatement.hpp"
#include "BinaryExpression.hpp"
#include "BlockPragma.hpp"
#include "Complex.hpp"
#include "DebugStatement.hpp"
#include "DPUChainPragma.hpp"
#include "DPUPragma.hpp"
#include "FloatingPoint.hpp"
#include "ForStatement.hpp"
#include "FunctionDeclaration.hpp"
#include "FunctionCall.hpp"
#include "Identifier.hpp"
#include "IfStatement.hpp"
#include "IfThenElseStatement.hpp"
#include "IndexInfo.hpp"
#include "Integer.hpp"
#include "LoopObjectDeclaration.hpp"
#include "MainProgram.hpp"
#include "NumericLiteral.hpp"
#include "ObjectDeclaration.hpp"
#include "PrimitiveFunctionCall.hpp"
#include "ParenthesizedExpression.hpp"
#include "PragmaExpression.hpp"
#include "PragmaStatement.hpp"
#include "RaccuPragma.hpp"
#include "RangeExpression.hpp"
#include "SliceName.hpp"
#include "StoragePragma.hpp"
#include "StringLiteral.hpp"
#include "TempVarPragma.hpp"
#include "UnaryExpression.hpp"
#include "UnrolledAddressInfo.hpp"
#include "Unrolling.hpp"
#include "FunctionCallStatement.hpp"
#include "AddressFunction.hpp"

#endif // __VIRIncludeAll_h__
