#line 2 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.flex.cpp"

#line 4 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[291] =
    {   0,
        0,    0,    0,    0,    0,    0,   90,   88,   19,   22,
       22,   88,   58,   81,   85,   86,   69,   67,   11,   68,
       88,   71,   17,   66,   12,   60,   87,   62,   23,   82,
       73,   84,   78,   23,   23,   23,   23,   23,   23,   59,
       79,   80,   89,   20,   40,   37,   38,   41,   39,   89,
       89,   89,   89,   89,   89,   42,   43,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   19,    0,
       22,   24,   25,    0,   13,   76,   70,    0,   72,   18,
       74,   77,   18,   17,    0,   14,   61,   64,   63,   23,
        0,    0,   23,   23,   23,   23,   23,    3,   23,   23,

       65,   20,   37,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,   24,   24,   10,   21,
        0,   16,   15,    0,   18,   83,   23,    2,    1,   23,
       23,   23,   23,    0,    0,    0,   28,   31,    0,    0,
        0,    0,    0,   55,    0,    0,    0,    0,    0,   44,
       45,    0,   54,   46,    0,   21,   21,    0,   18,    5,
       23,   23,   23,   23,    0,    0,   29,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,   23,   23,   23,    7,    0,    0,    0,    0,   30,

        0,    0,    0,    0,    0,    0,   51,    0,    0,    0,
        4,   23,    6,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   52,    0,    0,   23,    0,    0,
        0,    0,    0,   47,    0,    0,    0,    0,    0,    0,
        8,    0,    0,    0,    0,   34,    0,    0,    0,    0,
       26,    0,    0,    0,   33,    0,    0,   56,   48,   49,
        0,    0,    0,    0,    0,    0,    0,   27,    0,   32,
        0,   50,   57,    0,    0,   53,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   36,    0,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    1,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   33,   33,   33,   33,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   33,   59,   60,   61,
       62,   63,   33,   64,   65,   66,   67,   68,   69,   33,
       33,   33,    1,   70,    1,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    2,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    4,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[298] =
    {   0,
        0,    0,  422,  421,   70,  134,  429,  432,   74,   74,
       77,  422,  432,  418,  432,  432,  432,  432,  432,  432,
      191,  432,  113,  432,  432,  404,  403,  402,    0,  432,
      432,   81,  432,   26,   33,  364,  368,  368,  364,  432,
      397,  432,  432,  416,  432,  399,  356,  432,  432,  388,
      387,  375,  384,   78,  383,  432,  432,  358,   37,  352,
      340,  340,  345,  343,  337,  354,  340,   49,  110,  392,
      139,  142,  432,  391,  390,  432,  432,  382,  432,  174,
      432,  432,  230,  177,   95,  432,  432,  432,  432,    0,
      152,    0,  332,  344,  331,  333,  331,    0,  326,  334,

      432,  388,  371,  335,  360,  348,  343,  349,  357,  342,
      349,  345,  327,  319,  312,  316,  322,  315,  310,  320,
      305,  306,  300,  302,  303,  432,  146,  432,  432,  159,
      164,  432,  432,  348,  110,  432,  312,    0,    0,  313,
      313,  295,  302,  300,  320,  316,  432,  432,  331,  319,
      321,  316,  289,  432,  286,  298,  289,  290,  281,  432,
      284,  297,  432,  432,  278,  207,  432,  326,  158,  286,
      276,  292,  276,  286,  290,  309,  432,  294,  293,  306,
      285,  279,  269,  269,  281,  280,  261,  259,  266,  273,
      269,  265,  262,  259,    0,  270,  278,  269,  277,  432,

      272,  249,  253,  247,  246,  234,  432,  219,  225,  215,
        0,  218,    0,    0,  227,  238,  233,  248,  249,  207,
      223,  213,  212,  211,  432,  214,  199,  204,  212,  215,
      238,  233,  221,  432,  207,  194,  190,  189,  194,  188,
        0,  187,  207,  210,  198,  432,  188,  183,  177,  175,
      183,  188,  180,  204,  432,  185,  159,  432,  432,  432,
      158,  163,  156,  181,  188,  152,  157,  432,  149,  432,
      189,  432,  432,  183,  151,  432,  157,  148,  151,  124,
       61,  131,  117,   95,   93,   86,  432,   81,  432,  432,
      288,  292,  296,   98,  300,  304,  307

    } ;

static yyconst flex_int16_t yy_def[298] =
    {   0,
      290,    1,    1,    1,  291,  291,  290,  290,  290,  290,
      290,  292,  290,  293,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  294,  290,
      290,  290,  290,  294,  294,  294,  294,  294,  294,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  295,  290,  293,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  294,
      290,  296,  294,  294,  294,  294,  294,  294,  294,  294,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  295,  290,  290,  297,
      290,  290,  290,  290,  290,  290,  294,  294,  294,  294,
      294,  294,  294,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  297,  290,  290,  290,  294,
      294,  294,  294,  294,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      294,  294,  294,  294,  294,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      294,  294,  294,  294,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  294,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      294,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,    0,
      290,  290,  290,  290,  290,  290,  290

    } ;

static yyconst flex_int16_t yy_nxt[504] =
    {   0,
        8,    9,   10,   11,   11,    8,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   30,   31,   32,   33,   29,   29,   29,
       29,   29,   34,   35,   36,   29,   37,   29,   29,   29,
       29,   29,   29,   38,   29,   29,   29,   29,   39,   40,
       41,   44,   10,   10,   10,   69,   71,   71,   71,   71,
       71,   71,   91,   45,   93,  282,   94,   46,  283,   70,
       47,   48,   49,   50,   95,   51,   52,  124,  114,   96,

       90,  109,   92,  115,   53,  110,  111,  134,   54,  134,
       55,   69,  135,   56,  125,   57,  289,  288,   58,  287,
       59,   60,   61,   62,  286,   70,   63,  135,   83,   64,
       84,   65,   66,   67,   68,   44,   10,   10,   10,   85,
       85,   71,   71,   71,  128,  128,  128,   45,  128,  128,
      128,   46,  285,   91,   47,   48,   49,   50,  284,   51,
       52,  167,  167,  167,   85,   85,   86,   86,   53,   86,
       86,  281,   54,   92,   55,  169,  168,   56,  168,   57,
      280,  169,   58,  279,   59,   60,   61,   62,  278,  277,
       63,   80,   83,   64,   84,   65,   66,   67,   68,   76,

      131,  131,   77,   85,   85,  276,   78,   79,   80,  167,
      167,  167,  275,  274,   86,   86,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  131,  131,  264,   85,   85,
       86,   86,  263,   86,   86,   81,  262,   82,  132,  261,
      260,  133,  259,  258,  257,  256,  133,   80,  255,  254,
      253,  252,  251,  250,  249,  248,  131,  131,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  133,  231,  133,  230,  229,  228,
      227,  131,  131,  226,  225,  224,   86,   86,   43,   43,
       43,   43,   72,   72,   72,   72,   74,  223,   74,   74,

      127,  127,  127,  127,  136,  136,  136,  166,  166,  166,
      166,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  169,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  135,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  103,  102,
      143,  142,  141,  140,  139,  138,  137,  130,  129,   75,

      126,  123,  122,  121,  120,  119,  118,  117,  116,  113,
      112,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   89,   88,   87,   75,   73,  290,   42,
       42,    7,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290
    } ;

static yyconst flex_int16_t yy_chk[504] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    9,   10,   10,   10,   11,
       11,   11,   32,    5,   34,  281,   34,    5,  281,    9,
        5,    5,    5,    5,   35,    5,    5,   68,   59,   35,

      294,   54,   32,   59,    5,   54,   54,   85,    5,   85,
        5,   69,   85,    5,   68,    5,  288,  286,    5,  285,
        5,    5,    5,    5,  284,   69,    5,  135,   23,    5,
       23,    5,    5,    5,    5,    6,    6,    6,    6,   23,
       23,   71,   71,   71,   72,   72,   72,    6,  127,  127,
      127,    6,  283,   91,    6,    6,    6,    6,  282,    6,
        6,  130,  130,  130,   23,   23,  135,  135,    6,   23,
       23,  280,    6,   91,    6,  169,  131,    6,  131,    6,
      279,  131,    6,  278,    6,    6,    6,    6,  277,  275,
        6,   80,   84,    6,   84,    6,    6,    6,    6,   21,

       80,   80,   21,   84,   84,  274,   21,   21,   21,  166,
      166,  166,  271,  269,  169,  169,  267,  266,  265,  264,
      263,  262,  261,  257,  256,   80,   80,  254,   84,   84,
       80,   80,  253,   84,   84,   21,  252,   21,   83,  251,
      250,   83,  249,  248,  247,  245,   83,   83,  244,  243,
      242,  240,  239,  238,  237,  236,   83,   83,  235,  233,
      232,  231,  230,  229,  228,  227,  226,  224,  223,  222,
      221,  220,  219,  218,   83,  217,   83,  216,  215,  212,
      210,   83,   83,  209,  208,  206,   83,   83,  291,  291,
      291,  291,  292,  292,  292,  292,  293,  205,  293,  293,

      295,  295,  295,  295,  296,  296,  296,  297,  297,  297,
      297,  204,  203,  202,  201,  199,  198,  197,  196,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  176,  175,  174,  173,
      172,  171,  170,  168,  165,  162,  161,  159,  158,  157,
      156,  155,  153,  152,  151,  150,  149,  146,  145,  144,
      143,  142,  141,  140,  137,  134,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  102,
      100,   99,   97,   96,   95,   94,   93,   78,   75,   74,

       70,   67,   66,   65,   64,   63,   62,   61,   60,   58,
       55,   53,   52,   51,   50,   47,   46,   44,   41,   39,
       38,   37,   36,   28,   27,   26,   14,   12,    7,    4,
        3,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[90] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
#line 4 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"

/*
 *  Lexical specification for MATLAB 
 *  Command-line options: -f
 */

//! Yu Yang 2017-08-01
// After move bison/flex generation to CMAKE, the header file name changes
// CHANGE BEGIN
#include "vparser.tab.hpp"
// CHANGE END

#include "FlexUtility.hpp"
#include <ctype.h>


#define Return(value, token)  \
{                             \
  printLexToken(value);       \
  return token;               \
}

int gBracketDepth;

void yyinsert_comma_in_input(const int);



#line 719 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.flex.cpp"

#define INITIAL 0
#define TRANSPOSE_STATE 1
#define PRAGMA_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 58 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"



#line 907 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.flex.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 432 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("FOR", FOR);
                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("END", END);
                                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("IF", IF);
                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("ELSEIF", ELSEIF);
                                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("ELSE", ELSE);
                                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("GLOBAL", GLOBAL);
                                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("WHILE", WHILE);
                                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("FUNCTION", FUNCTION);
                                }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 109 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("RETURN", RETURN);
                                }
	YY_BREAK
case 10:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 115 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  yymore();
                                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 121 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("','", ',');
                                }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 128 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("';'", ';');
                                }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 135 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  // TODO: THIS PART HAS BEEN MODIFIED

                                  int i, size;
                                  char* modified;
                                  const int length = yyleng-2;

                                  for (size = 0, i = 1; i <= length; size++, i++)
                                    if (*(yytext+i) == '\'')
                                      i++;

                                  modified = new char [size + 1];
                                  *(modified+size) = '\0';

                                  for (size = 0, i = 1; i <= length; size++, i++)
                                  {
                                    *(modified+size) = *(yytext+i);

                                    if (*(yytext+i) == '\'')
                                      i++;
                                  }

                                  yylval.text = modified;

                                  Return("TEXT", TEXT);
                                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 164 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);

                                  *(yytext+yyleng-1) = '\0';

                                  yylval.imaginaryVal = atoi(yytext);

                                  Return("IMAGINARY", IMAGINARY);
                                }
	YY_BREAK
case 15:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 176 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  yylval.integerVal = atoi(yytext);

                                  Return("INTEGER", INTEGER);
                                }
	YY_BREAK
case 16:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 184 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  yylval.integerVal = atoi(yytext);
                                  Return("INTEGER", INTEGER);
                                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 191 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);

                                  yylval.integerVal = atoi(yytext);
                                  yyinsert_comma_in_input(INTEGER);

                                  Return("INTEGER", INTEGER);
                                }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 202 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);

                                  yylval.doubleVal = atof(yytext);

                                  Return("DOUBLE", DOUBLE);
                                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 212 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 217 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 222 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  GlobalValues::gSourceLine++;
                                }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 228 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  GlobalValues::gSourceLine += yyleng;
                                  Return("LINE", LINE);
                                }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 236 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);

                                  yylval.symbol = new char [yyleng + 1];
                                  strncpy(yylval.symbol, yytext, yyleng + 1);

                                  yyinsert_comma_in_input(IDENTIFIER);

                                  Return("IDENTIFIER", IDENTIFIER);
                                }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 249 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  GlobalValues::gSourceLine++;

                                  Return("LINE", LINE);
                                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 258 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  //cout<<"\nPragma detected!\n";

                                  BEGIN(PRAGMA_STATE);
                                  Return("PRAGMASTART", PRAGMASTART);
                                }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 266 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("PARALLEL", PARALLEL);
                                }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 271 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("STRUCTURAL", STRUCTURAL);
                                }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 276 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("DPU", DPU);
                                }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 281 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("CDPU", CDPU);
                                }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 286 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("RFILE", RFILE);
                                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 291 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("MEMORY", MEMORY);
                                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 296 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("ADDRESS_VAR", ADDRESS_VAR);
                                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 302 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  //BEGIN(INITIAL);
                                  Return("RACCU_VAR", RACCU_VAR);
                                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 308 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("TEMP_VAR", TEMP_VAR);
                                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 314 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("RESOURCE_SHARING_BEGIN", RESOURCE_SHARING_BEGIN);
                                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 320 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("RESOURCE_SHARING_END", RESOURCE_SHARING_END);
                                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 326 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  yylval.integerVal = atoi(yytext);
                                  yyinsert_comma_in_input(INTEGER);

                                  Return("INTEGER", INTEGER);
                                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 334 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("'<'", '<');
                                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 339 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  //BEGIN(INITIAL);
                                  Return("'>'", '>');
                                }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 345 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("','", ',');
                                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 350 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("'='", '=');
                                }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 355 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("'['", '[');
                                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 361 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("']'", ']');
                                }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 366 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("DPUMODE", DPUMODE);
                                }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 371 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("DPUOUT", DPUOUT);
                                }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 376 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("DPU_SATURATION", DPU_SATURATION);
                                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 381 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("ADDRESS", ADDRESS_REG);
								}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 386 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("EVENDIST", EVENDIST);
                                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 391 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("FULLDIST", FULLDIST);
                                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 396 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("CUSTOMDIST", CUSTOMDIST);
                                }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 401 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("VAR_INPUT", VAR_INPUT);
                                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 406 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("VAR_OUTPUT", VAR_OUTPUT);
                                }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 411 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
								  BEGIN(INITIAL);
                                  Return("MEM_ADDRESS", MEM_ADDRESS);
                                }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 418 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("CONSTROW", CONSTROW);
                                }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 425 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("CONSTCOL", CONSTCOL);
                                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 432 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("CONSTDIMENSION", CONSTDIMENSION);
                                }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 439 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("CONSTPARALLELISM", CONSTPARALLELISM);
                                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 446 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("AND", AND);
                                }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 453 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("OR", OR);
                                }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 460 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("LTHAN", LTHAN);
                                }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 467 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("LTHANE", LTHANE);
                                }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 474 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("GTHAN", GTHAN);
                                }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 481 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("GTHANE", GTHANE);
                                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 488 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("EQUAL", EQUAL);
                                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 495 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("UNEQUAL", UNEQUAL);
                                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 502 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("':'", ':');
                                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 509 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("'+'", '+');
                                }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 516 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("'-'", '-');
                                }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 523 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("MMUL", MMUL);
                                }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 530 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("EMUL", EMUL);
                                }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 537 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("MDIV", MDIV);
                                }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 544 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("EDIV", EDIV);
                                }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 551 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("MLEFTDIV", MLEFTDIV);
                                }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 558 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("ELEFTDIV", ELEFTDIV);
                                }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 565 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("LEXERROR", LEXERROR);
                                }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 571 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);
                                  Return("TRANSPOSE", TRANSPOSE);
                                }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 578 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("EPOWER", EPOWER);
                                }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 585 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("MPOWER", MPOWER);
                                }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 592 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("NOT", NOT);
                                }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 599 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("CTRANSPOSE", CTRANSPOSE);
                                }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 605 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  Return("LEXERROR", LEXERROR);
                                }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 611 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  if (gBracketDepth)
                                  {
                                    gBracketDepth++;
                                    Return("'['", '[');
                                  }

                                  int current = 0, next = 0;
                                  char* buffer = 0;
                                  int level = 1, length = 0;

                                  while (level && (current = yyinput()) != EOF)
                                  {
                                    buffer = realloc_string(buffer, ++length);

                                    *(buffer+length-1) = current;

                                    if (current == '[')
                                      level++;

                                    if (current == ']')
                                      level--;
                                  }

                                  if (level)
                                    Return("LEXERROR", LEXERROR);

                                  while ((current = yyinput()) != EOF)
                                  {
                                    buffer = realloc_string(buffer, ++length);

                                    *(buffer+length-1) = current;

                                    if (current != ' ' && current != '\t')
                                      break;
                                  }

                                  if ((next = yyinput()) != EOF)
                                  {
                                    buffer = realloc_string(buffer, ++length);

                                    *(buffer+length-1) = next;
                                  }

                                  for (; length > 0; length--)
                                    unput(*(buffer+length-1));

                                  free(buffer);

                                  gBracketDepth = 1;

                                  if (current == '=' && next != '=')
								                  {
                                    Return("LD", LD);
								                  }
                                  else
								                  {
                                    Return("'['", '[');
								                  }
                                }
	YY_BREAK
case 83:
/* rule 83 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 674 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  gBracketDepth--;
                                  Return("RD", RD);
                                }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 682 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);
                                  gBracketDepth--;
                                  Return("']'", ']');
                                }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 690 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("'('", '(');
                                }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 697 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(TRANSPOSE_STATE);
                                  Return("')'", ')');
                                }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 704 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
BeginToken();
                                  BEGIN(INITIAL);
                                  Return("'='", '=');
                                }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 711 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
{
                                  Return("LEXERROR", LEXERROR);
                                }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 716 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"
ECHO;
	YY_BREAK
#line 1887 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.flex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TRANSPOSE_STATE):
case YY_STATE_EOF(PRAGMA_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 290);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 716 "/home/herenvarno/Projects/gitr/SiLago/vesyla/src/VParser/vparser.l"



void yyinsert_comma_in_input(const int lastToken) {

  int count, current, next;

  extern int gBracketDelimiter;

  printLexMessage("\nEntering<yyinsert_comma_in_input> ...\n");

  if (!(gBracketDelimiter == '[' || gBracketDelimiter == LD))
    return;

  for (count = 1; ; count++) 
  {
    current = yyinput();

    if (current != ' ' && current != '\t')
      break;
  }

  if (current == ','  || current == ';'  || current == ']'  ||
      current == '*'  || current == '^'  || current == ':'  ||
      current == '<'  || current == '>'  || current == '='  ||
      current == '&'  || current == '|'  || current == '/'  ||
      current == '\\' || current == '\n' || current == '\r' ||
      current == '\f' || current == '%'  || (current == '\'' && count == 1))
  {
    unput(current);
    return;
  }

  if (current == '(' && (gBracketDelimiter == LD || (lastToken == IDENTIFIER && count == 1)))
  {
    unput(current);
    return;
  }

  if (isalpha(current) && (lastToken == INTEGER || lastToken == DOUBLE) && count == 1)
  {
    unput(current);
    return;
  }

  next = yyinput();
  ++count;

  if (current == '.' &&
      (next == '\'' || next == '*' || next == '^' ||
       next == '/'  || next == '\\' || next == '.'))
  {
    unput(next);
    unput('.');

    if (next == '\'' && count > 2)
      unput(' ');

    return;
  }

  if (current == '~' && next == '=')
  {
    unput('=');
    unput('~');

    return;
  }

  if (current == '+' || current == '-')
    if (count == 2 || next == ' ' || next == '\t')
    {
      unput(next);
      unput(current);

      return;
    }

  unput(next);
  unput(current);
  unput(',');
}

