
#ifndef __BIRIncludeAll_h__
#define __BIRIncludeAll_h__

#include "AGU.hpp"
#include "BIRBase.hpp"
#include "BIRKindType.hpp"
#include "BranchInstruction.hpp"
#include "BranchMode.hpp"
#include "ContileCell.hpp"
#include "DiMArch.hpp"
#include "DiMArchCell.hpp"
#include "DPU.hpp"
#include "DPUInstruction.hpp"
#include "DPUMode.hpp"
#include "DRRACell.hpp"
#include "DRRACluster.hpp"
#include "LoopHeaderInstruction.hpp"
#include "LoopTailInstruction.hpp"
#include "JumpInstruction.hpp"
#include "MemElement.hpp"
#include "RACCU.hpp"
#include "RACCUInstruction.hpp"
#include "RACCUMode.hpp"
#include "RefiInstruction.hpp"
#include "Refi1Instruction.hpp"
#include "Refi2Instruction.hpp"
#include "Refi3Instruction.hpp"
#include "Register.hpp"
#include "RegFile.hpp"
#include "RFILEInstruction.hpp"
#include "RouteInstruction.hpp"
#include "Sequencer.hpp"
#include "SRAM.hpp"
#include "SRAMInstruction.hpp"
#include "SWBInstruction.hpp"
#include "SwitchBox.hpp"
#include "ValueWithStaticFlag.hpp"
#include "WaitInstruction.hpp"
#include "DpuParameterType.hpp"

#endif // __BIRIncludeAll_h__
